
format = "$directory$git_branch$git_status$character"

[directory]
style = "cyan"
format = "[$path]($style) "
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = " "
style = "magenta"
format = "on [$symbol$branch]($style) "

[git_status]
style = "red"
format = "[$all_status]($style) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "

# Turn off everything else
[username]
disabled = true

[hostname]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[time]
disabled = true
